// Restaurant data for our Copenhagen date night — Friday, October 2nd 2026.
// Times are REAL availability for a table of 2, walked through each
// restaurant's own booking system on 29 Sep 2026. Interior photos are
// referenced from each venue's own site / Google Maps listing to show the vibe.

const RESTAURANTS = [
  {
    id: "scarpetta",
    name: "Scarpetta",
    cuisine: "Italian trattoria",
    area: "Nørrebro",
    address: "Rantzausgade 7, 2200 København N",
    rating: 4.3,
    reviews: 997,
    pesc: {
      level: "great",
      note: "Loads of pasta, pizza, veg & seafood (shrimp linguine, burrata, arancini). Only the ribeye is meat.",
    },
    imgs: [
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmizevpMbqmcr-Thz0YsOfX6m8Jzqlo2VYN6ib1si5N2otvPqkQctQ0vGQdsgnnqPEgJSxHdt8I_J7e0xCYzrhbLt23bi-lVY3ZA5r20hV1pJ3j6dnn71e_vGSzwoHO7_WeV8zQaT3-pUQ=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9Sp72_REHM0_z5cTT5wePnrM0bxOwKQxyYD5Wfh7gF22nFc-Cjr6HcKuHRy0hOZ14YDEx3I4i5cbjP39dE7NDMmnmObSJKUKESRcSBTVSKKds3Ujc6auYqo-4DQJy6JITP1yNJvw4icHx4=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9THG-eJObD6pXdDB-qfDXgz8y-Tp7NZ6hIFEkxYnyRl7tg5_p650maiJl3N4ivKpgUt3bb7A5t7rbKi7fq5q15mJrDc3y3D_XYENFlTrw-cGlbHHM2ktUyWXaNTgc1IyJxe4rfjnFKjN1k=w1200-h900-k-no",
    ],
    blurb:
      "Cosy COFOCO trattoria on Rantzausgade — green benches, plates on the walls, wood-fired pizza and a lively neighbourhood buzz.",
    friday: {
      window: "Fri 2 Oct · bookable for 2: 17:30 or 20:15–21:15",
      slots: ["17:30", "20:15", "20:30", "20:45", "21:00", "21:15"],
    },
    menu: [
      "Burrata with tomatoes, pine nuts & basil",
      "Arancini with salsa rosso & parmesan",
      "Margherita & Salame Piccante pizza (gluten-free available)",
      "Linguine with wild shrimp & chili",
      "Ricotta & truffle ravioli",
      "Grilled ribeye with pepper sauce",
      "Tiramisu · Lemon meringue pie",
    ],
    website: "https://cofoco.dk/en/restaurant/scarpetta-rantzausgade",
    bookUrl: "https://bordibyen.dk/book/5?lang=english",
    menuUrl: "https://cofoco.dk/en/restaurant/scarpetta-rantzausgade#menu",
    maps: "https://maps.app.goo.gl/hs3WexT6SSykQF4a6",
    phone: "+45 35 35 08 08",
  },
  {
    id: "llama",
    name: "Llama",
    cuisine: "Latin American",
    area: "Indre By (city centre)",
    address: "Lille Kongensgade 14, 1074 København K",
    rating: 4.4,
    reviews: 3095,
    pesc: {
      level: "some",
      note: "Ceviche, Baja cod tacos, tostadas & veg sides are lovely — but the menu leans heavily to flame-grilled meats.",
    },
    imgs: [
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9TpVO7sbOGz0YtK3Q6HfqQCkkTOvT9p3JKZFQoN97AVJaLHqwIvmV6W-fxWyJzSS83i26Qkib-LtNKCmUHwXvQLUo564Y8O-72pxy4yYtklmKy4rQ47TJV5xMd_Yfz8Nlwb2rFP=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9R-GtQZ1OqEONviSP7L5ZsQClQfsvu4oDBr27Aq8pc0cBG9EWhQZkMb9fOJqV6fwIjMmwdH14dKeVSkhierECiyOoFe6LVGGjKZiPske4g0kSixeWjKK3vQ4qCLlBDx7KPkoppqHsJxOiDh=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9Rlrl9Tm8f9lCndTIuyIAhPIQwt1qprLDLSnZfssl_s3DBHZkNPKm1EzfVZ9XtsAC_iyQQLSS6p16VyTVLYVYUIx0_XMysaG7UD_3rz-nwu3rrWVxB7ND51P79DN0lOjYPxMbFDq2D75h9g=w1200-h900-k-no",
    ],
    blurb:
      "Colourful South-American kitchen & cocktail bar behind a glowing neon sign — ceviche, tacos and flame-grilled skewers. 'Llama After Hours' with a DJ from 21:00 on Fridays.",
    friday: {
      window: "Fri 2 Oct · bookable for 2: 17:30–21:30 (DJ from 21:00)",
      slots: ["17:30", "17:45", "18:15", "18:30", "20:15", "20:30", "20:45", "21:00", "21:15", "21:30"],
    },
    menu: [
      "Prawn ceviche with avocado & chili",
      "Braised pork carnitas tacos",
      "Baja-style cod tacos",
      "Grilled beef skewers with ají panca",
      "Empanadas & flame-grilled meats",
      "Pisco sours & mezcal cocktails",
      "Coconut sorbet · churros with dulce de leche",
    ],
    website: "https://cofoco.dk/en/restaurant/llama",
    bookUrl: "https://bordibyen.dk/book/201?lang=english",
    menuUrl: "https://cofoco.dk/en/restaurant/llama#menu",
    maps: "https://maps.app.goo.gl/CSntmZGDfTXKZrQh9",
    phone: "+45 89 93 66 87",
  },
  {
    id: "spuntino",
    name: "Restaurant Spuntino",
    cuisine: "Italian",
    area: "Vesterbro",
    address: "Vesterbrogade 68, 1620 København V",
    rating: 4.2,
    reviews: 840,
    pesc: {
      level: "great",
      note: "Pizza, pasta, baked cod & plenty of veg. Only the ribeye is meat — easy for pescetarians.",
    },
    imgs: [
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlTxJ8a-RH-af23Hkn1qNjipTwosREosTTL-0uuymtVkamrHAoD6mG2_0ckSiDynTn1f83ynWZ4qcbq3aKKaKRpDRn4XlTRJXVI0MEDX0TQQyraq6jS0XOR3WNzIdtQYykZQ3p1PJUscXse=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlzeEcYNiSH1KNFm4wSly-fT617UPsC0x42O863tx3XGl-3kpTIDtpqaiU3-opWypQ7MyavCsyKHNcx98acfWEAGPklRu19INIiuNsdhjiTAyigk6iAu9ZIt_bCJZfuL1kb573Vqmak6hhO=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlTYcK_9U-YUSide71DH2al5p6eNZaXFutm8n3xScHw9McxSCYMByd3uqkvI_WbarG7-Mwr4MLvXzXIbv5DdqIoK5JMi2bpwadQtCz9E992DMvOm1acEwe--wZGh1fnSOzSfe0KxFIi3DbT=w1200-h900-k-no",
    ],
    blurb:
      "Pretty room with pink walls, trailing ivy and warm sunlight — Neapolitan pizza, homemade pasta and Italian classics served family-style.",
    friday: {
      window: "Fri 2 Oct · bookable for 2 from 17:30",
      slots: ["17:30", "17:45", "18:00", "18:15", "18:30", "19:45", "20:15", "20:30", "20:45", "21:00", "21:15"],
    },
    menu: [
      "Veal carpaccio",
      "Arancini with tomato, pesto & parmesan",
      "Bruschetta with grilled figs & ricotta",
      "Rigatoni alla vodka",
      "Spinach & ricotta ravioli",
      "Grilled ribeye · baked cod",
      "Tiramisu · panna cotta · lemon sorbet",
    ],
    website: "https://cofoco.dk/en/restaurant/spuntino",
    bookUrl: "https://bordibyen.dk/book/4?lang=english",
    menuUrl: "https://cofoco.dk/en/restaurant/spuntino#menu",
    maps: "https://maps.app.goo.gl/r6mk6zRinNe18c5NA",
    phone: "+45 70 20 50 89",
  },
  {
    id: "olise",
    name: "Olise",
    cuisine: "Modern bistro & wine",
    area: "Vesterbro",
    address: "Vesterbrogade 41, 1620 København V",
    rating: 4.7,
    reviews: 103,
    pesc: {
      level: "great",
      note: "Mussels, tuna crudo, grilled mullet & gnocchi — a strong seafood + veg list. Just skip the pepper steak & chicken.",
    },
    imgs: [
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlwugD-i2Dhq3T5uQ2z2eNDijbMHIDAB0bZ1tK5t54jUMhbyQ54KuyDM2VoZPQnE2VrK1fE-cykU9_Z8s3kW5oIYC1ZfiGAEiF1XMFWOQGt-6cMFy_0XV_xSHw1aDBhPtEUILv_Lqdeu3nW=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmhdN65NzVs5Hxm4mmDDR789bzrCDj2jbxDnH_eeF3-9NQ-R525LXOmTH5uO773JEf-yzesBLCts6dMfcx1jK_O1tL5h7Mh8ax8ImO22hePfG_DBb0e6sb2dtlZQc22TqoaA_wi5SO1HJPD=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlvvhNr2DLvyl6SRP2lqoh0IQa8JJta6oMEjCWM626hiWRtwmDTrpxtKhEjyyhWtafUV9a9bQFpI_F8DfZK0bESZg4OzorT1u-5ggiykGu3Ck2cZJuIHFjbcQ_sDlKYE6Y7lfQ6xdpzdO1p=w1200-h900-k-no",
    ],
    blurb:
      "Modern bistro with an open kitchen, green courtyard and a serious wine list — seasonal set menus in a relaxed, light-filled room.",
    friday: {
      window: "Fri 2 Oct · bookable for 2: early 17:30 or late from 20:30",
      slots: ["17:30", "20:30", "20:45", "21:00", "21:15", "21:30"],
    },
    menu: [
      "Marinated olives, almonds & gougères with truffle cream",
      "Steak tartare",
      "Tuna crudo · Moules d'Olise",
      "Roasted gnocchi with chanterelles & black truffle",
      "Grilled mullet · grilled chicken with leeks",
      "Pepper steak (tenderloin)",
      "3- and 4-course set menus available",
    ],
    website: "https://cofoco.dk/en/restaurant/olise",
    bookUrl: "https://bordibyen.dk/book/1751?lang=english",
    menuUrl: "https://cofoco.dk/en/restaurant/olise#menu",
    maps: "https://maps.app.goo.gl/6Wp2TycFVopq5hSE8",
    phone: "+45 31 31 41 41",
  },
  {
    id: "boutique-emilia",
    name: "Boutique Emilia",
    cuisine: "Italian handmade pasta",
    area: "Indre By (city centre)",
    address: "Frederiksholms Kanal 4, 1220 København K",
    rating: 4.9,
    reviews: 386,
    pesc: {
      level: "veg",
      note: "Book the 'Vegetarian Experience' — the standard tasting menu includes pork and can't be changed. The veg menu is meat-free (no fish either).",
    },
    imgs: [
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9RMpeapDAIPWYadKq4DnEPSnL0IRqNolaWCTDXbg4g5YdXQNIct2tPDDQW9VXCJJaiG50Q67zATxFCsNyjow94wE1fzuNz69HLs3N1f_FK2x0tBtS2LeIKbt0ELSbb2t1oarI3c=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9Sh5blGPwy_BPe2Q7uoelLs31lcNeuxBIkvTVWuRIZkh2GILbmOmDw4yaQKr5Tq4QtjoYVnhfMV7jjbA9XTtgrO0LgFY3c4J73C5mVA8vSsaXCF82Bhv3_wgzff8TDX5j26Qdheyw=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9S1f9WENOOA7E3lt4aYAjzcDR5Uwn_bddAGtp13JOLqUT5NRKdr9lepLWqeRZG8dwxYZ40-g8ytNDgFz1XkOqCkfMUQ5iZ_P5bFDfpzhQg_RRLxWXgaflDU-87WxlDOa4-ZqYvQA1A77sod=w1200-h900-k-no",
    ],
    blurb:
      "Intimate little boutique dedicated to handmade pasta from Emilia-Romagna — tiny, romantic, with shelves of Italian goodies. Reservation-only in feel.",
    friday: {
      window: "Fri 2 Oct · bookable for 2 (tasting menu, 2.5h seating)",
      slots: ["17:00", "17:15", "17:30", "19:45", "20:00", "20:15"],
      note: "Booking is for a set tasting menu (Boutique Emilia Experience). Card required — 500 DKK/person hold, charged only for late cancel/no-show.",
    },
    menu: [
      "Crescentina e salame rosa",
      "Liquid caprese",
      "Tortellino all'ascolana",
      "Parma & citrus ravioli (ricotta, Parma ham, yuzu butter)",
      "Balanzoni (ricotta, mortadella, pistachio butter)",
      "Signature tortellini · Parmigiano cream, balsamic & truffle 'caviar'",
      "Traditional tiramisu · lemon cheesecake",
    ],
    website: "https://www.boutiqueemilia.com/food",
    bookUrl: "https://www.boutiqueemilia.com/",
    menuUrl: "https://www.boutiqueemilia.com/food",
    maps: "https://maps.app.goo.gl/M6spyE9sjUWd6b1F9",
    phone: "+45 61 76 33 36",
  },
  {
    id: "donna",
    name: "Donna Restaurant",
    cuisine: "Italian",
    area: "Indre By (city centre)",
    address: "Vester Voldgade 25, 1552 København V",
    rating: 4.3,
    reviews: 679,
    pesc: {
      level: "great",
      note: "Burrata, baccalà (salt cod), pasta, pizza & veg — very easy for pescetarians.",
    },
    imgs: [
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmqKxLIzXCZgIcTNXGo_i9_1uuNjm7l08UG2vgIkhexcdHqjBAwbwk3ygqgFxZToGhRjjZdeYYOZUUL84jdz82dQ4zEU9FCyglYWa1Sjuzsi0-YNzIpYh8l0BOKWgd7g9msSEMbmVNtNXZE=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmePw4NTgOw8nmsAu1M3A5S1iid4xGscGa041cc5SjJ6R-gRLzpJZHzooIZie4dxaE_Tn0s5rZr896eDyaEcbIihciB-r5o8d54sDwvnTPWSb-u8FTsH7doeYHuLfjn4P_dWdaw_pIEChAB=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmXaj0lAuFaevkPYtlPK7tqewxJtiszmPKnnzxyrBB3wPFQHD7CAUsZygL5bx8l_v2tnO0MTqPfXCOp0zo-lutW9s6YCoQDVzLwbZocMv2bCH1QhnQt4qey6GWJ4T-YBgVeR1drmU4tGE9V=w1200-h900-k-no",
    ],
    blurb:
      "Wildly pretty Italian at Hotel Bella Grande — a jewel-box pink-and-red dining room with velvet chairs, mirrors and a glass-roofed atrium.",
    friday: {
      window: "Fri 2 Oct · dinner nearly full for 2 — only 21:15 (lunch 11:30–14:30 open)",
      slots: ["21:15"],
      note: "Dinner is almost fully booked for 2; 21:15 is the only evening slot. Plenty of lunch slots 11:30–14:30 if you fancy a daytime date.",
    },
    menu: [
      "Caprese burrata · baccalà",
      "Rigatoni alla vodka",
      "Ravioli con ricotta e spinaci",
      "Margherita & salame piccante pizza",
      "Menu di Donna (chef's tasting)",
      "Tiramisu · panna cotta",
    ],
    website: "https://cofoco.dk/en/restaurant/donna",
    bookUrl: "https://bordibyen.dk/book/1454?lang=english",
    menuUrl: "https://cofoco.dk/en/restaurant/donna#menu",
    maps: "https://maps.app.goo.gl/uUwxefRxtGbj7Uas5",
    phone: "",
  },
  {
    id: "osteria16-haderslevgade",
    name: "Osteria 16 · Haderslevgade",
    cuisine: "Italian (set antipasti menu)",
    area: "Vesterbro",
    address: "Haderslevgade 16, 1671 København V",
    rating: 4.5,
    reviews: 626,
    pesc: {
      level: "some",
      note: "Set antipasti menu; vegetarian & gluten-free options are available on request, but the fixed menu can include cured meats — give them a heads-up when booking.",
    },
    imgs: [
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkgHMr0kY-2nqe4f2QRTj8UOhBGhnl_8BHC-zhvseZ2AYTVxaWVstKrc2lyjYHABjVPNwRw8mFgZJz8ZNp5c8xLhW1i5opKdl5FbqrnsseERdGL6FHF3kFdUTXj7PNfzJoWVdEx=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9QEj2nkP0uo-zhlQHgR6dR67Qj5i6KztqVQjr_xzF624xjGXz4F8n73teOHevX5v2Ghgd27LGUJ0uB_lBvRJIexggZ-Lbc7GM97_Io3uBrBwjbH87qr2m_vYUwkWLjKmI6h1kx0SP6igF0B=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9QlJ15aAd4vKBK5ieP91l3DcrXcl38qA_hGG1RpGC6r_nlMsTn8fcfIWBQaj1tPnOfLyboHA8cRerisW2HIjNW0VAZRR14cnH5tH9rJty4J8lOxyNyP5D7dq3njSUbmV4BHPjlhXdySaOev=w1200-h900-k-no",
    ],
    blurb:
      "The original Osteria 16 (2014) — a snug 35-seat room with an open kitchen, imported-from-Italy antipasti and a small natural-wine list.",
    friday: {
      window: "Fri 2 Oct · only 17:00 bookable for 2 (rest waitlist)",
      slots: ["17:00"],
      note: "Just the 17:00 seating is open for 2 (2h table); other times are waitlist only. Fri hours 17:00–01:00. Menu: 8 antipasti + dessert.",
    },
    menu: [
      "8 seasonal antipasti (set menu, ~380 DKK)",
      "Signature handmade pasta of the day",
      "Fresh produce imported from Italy",
      "House red & white from their own Piemonte vineyard",
      "Traditional & natural wines",
      "Dessert of the day",
    ],
    website: "https://shop.fresto.io/en/osteria-16-h/booking",
    bookUrl: "https://shop.fresto.io/en/osteria-16-h/booking",
    menuUrl: "https://osteria16.dk/blurosth.html",
    maps: "https://maps.app.goo.gl/r1JM7dHqRb4kb9ne6",
    phone: "+45 33 21 60 60",
  },
  {
    id: "osteria16-ravnsborggade",
    name: "Osteria 16 · Ravnsborggade",
    cuisine: "Italian (set antipasti menu)",
    area: "Nørrebro",
    address: "Ravnsborggade 14B, 2200 København N",
    rating: 4.5,
    reviews: 197,
    pesc: {
      level: "some",
      note: "Set antipasti menu; vegetarian options available on request, but the fixed menu can include cured meats — mention it when booking.",
    },
    imgs: [
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9SElOteXl3g4pUsrd4ngBmKdhvxwhgrJN8LRlihC9zIbKTHzkCXw7uiGxkqpEwZEKuzqlfK3tam_onWfA5suf6hx0I43o3KgHG8ZQVLADvnQ3CrXd2-dyCMY2o2pWHg5LWNm0tIcg=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9SgLL456YD4JWU1l23mbWi0MfwHQuzfnQwxwS79NdzsgRBLgBQ7DBgrP9UUUPVCMaG0JaRV7wKjXlWgd-p5sYYO63NQLJoKIfSaaHdOGsxAGIzVrmD67qkODCc40aM6TFvdK8G59g=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9RXEeUqx_hw8tUzwx5Ny7fuqTQR-GrcVJHfoNGwjPhQuROqk5KeAteMdaPzKuK5Q3HsSLyURXgRtEq9RYrUZg99fXrivglBvzCR-y3IWCjBQwEUzVsWcdpXwIPIj6AYJ6wWBjzpZHYYv_yv=w1200-h900-k-no",
    ],
    blurb:
      "The Nørrebro sibling of Osteria 16 — same warm, candlelit trattoria vibe and seasonal Italian antipasti, on buzzy Ravnsborggade.",
    friday: {
      window: "Fri 2 Oct · bookable for 2: 17:00, 20:45 or 21:30",
      slots: ["17:00", "20:45", "21:30"],
      note: "Open Mon–Sun 17:00–00:00. Menu: 7 antipasti + 1 primo, 385 DKK.",
    },
    menu: [
      "7 antipasti + 1 primo (set menu, 385 DKK)",
      "Theatre / quick menu: 3 antipasti + 1 primo (265 DKK)",
      "Seasonal Italian small plates",
      "Traditional & natural wines",
      "House wine from their Piemonte vineyard",
      "Tiramisu",
    ],
    website: "https://shop.fresto.io/en/osteria-16-ravnsborggade/booking",
    bookUrl: "https://shop.fresto.io/en/osteria-16-ravnsborggade/booking",
    menuUrl: "https://osteria16.dk/blurravns.html",
    maps: "https://osteria16.dk/ravnsborggade.html",
    phone: "+45 33 22 60 61",
  },
  {
    id: "osteria16-sonderboulevard",
    name: "Osteria 16 · Sønder Boulevard",
    cuisine: "Italian (set antipasti menu)",
    area: "Vesterbro",
    address: "Sønder Boulevard 54, 1720 København V",
    rating: 4.5,
    reviews: 178,
    pesc: {
      level: "great",
      note: "This is Osteria 16's all-seafood 'Pesce' concept — the whole set menu is Italian fish & seafood antipasti. Basically made for pescetarians. 🐟",
    },
    imgs: [
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9SCZ4ZDna_s9hk7zjSM6bauebbmhlR050EomDUqA-S1YzQWSI702SCfOFoxHW4myMrG3tKYteF72Bdw7OuJJYxKpjY35rMMcly5_JE_wXt7BA4z-391jrJbEBmtEOyJM9NeJOx-r4laEw=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9RGQ0TKat5iBiyAxXHr_THNbSHbqv_lPNWy1d4LQESoraFUozUPD3SBvu14AYFyefiXynC7IOHn5ERSCy96KECq5fMIztfK-2r2YCG_DgoHmXnOaCZjSe2l_RgnAm-O40_0jfqWU_7w22o=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/ANWiy9QIvWR1CX_J5OwXuaZjcqOu7rd-vbBrniB5LA0NFng3BrWhFyC9t-ZliRJXSnA8oFdWX7hbnb1mYf1igGfborguHVTIEXag_X9itGdKPHdFBP8vnOYsJo0OR_P2WXLxYiUWL_u1uoTX8dxG=w1200-h900-k-no",
    ],
    blurb:
      "Osteria 16's seafood spot, 'Pesce' — a fixed menu of Italian fish & seafood antipasti (about 6 small plates + a pasta), all 'today's catch'. Closed Sundays.",
    friday: {
      window: "Fri 2 Oct · only 17:00 bookable for 2 (rest waitlist)",
      slots: ["17:00"],
      note: "Just the 17:00 seating is open for 2 (2h table); other times are waitlist only. Fri hours 17:00–22:00. All-seafood set menu: 6 antipasti + 1 primo, 390 DKK.",
    },
    menu: [
      "Seasonal fish & seafood antipasti (set menu, 390 DKK)",
      "Today's catch — shellfish, molluscs & crudo",
      "Fresh pasta with seafood",
      "Coastal-Italy style, sourced for freshness",
      "Mostly Italian wine list, matched to the menu",
      "Tiramisu",
    ],
    website: "https://shop.fresto.io/en/osteria-16-pesce/booking",
    bookUrl: "https://shop.fresto.io/en/osteria-16-pesce/booking",
    menuUrl: "https://osteria16.dk/blurpesce.html",
    maps: "https://osteria16.dk/sonderboulevard.html",
    phone: "+45 33 22 70 71",
  },
  {
    id: "cleo",
    name: "Cleo",
    cuisine: "Modern shared plates",
    area: "Nørrebro",
    address: "Rantzausgade 58B, 2200 København N",
    rating: 4.4,
    reviews: 222,
    pesc: {
      level: "great",
      note: "Already mostly pescatarian & vegetarian shared plates — basically made for you two. 💚",
    },
    imgs: [
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn5DNltVgNQydBq-WhkAKspB2uYS3FMROJoRrGAapJckLkhuOcGg-3bQ4_aQzZGYO1_VkUtX1yIf-ajSM89ghk7mxaglaDfYkDAsZ9X53UiG2H9y9J39iVXEC6ZEUkBhFJPvprNf4UmCJSO=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm_eAEqTjYscLmFnL0KdVqzOkHuyZcBW4QDYftNmIY-IaAXJ7-yrPmDCnXG2hdqCinIylnDsNxVyu1WdjpRO35tiCDOqXjjau1oVYlhkuF3ZHn5bag37yti2zFCbokMNCguFimq=w1200-h900-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnnyGO99_jBJEW0ot6AsayKOmQWmAtFpqA402V8TQpiIWAEXQB7PwVlssuCXvFQEumECK9T7fV8rBkav5Sxu7oYxMCIN-cFb7z_QsOBhKFwfa0SHnGmSRVB_-p0ISGXOLuLevI150xR7COE=w1200-h900-k-no",
    ],
    blurb:
      "Creative, mostly pescatarian/vegetarian shared plates with playful fusion touches — an open-kitchen, buzzy Nørrebro favourite.",
    friday: {
      window: "Fri 2 Oct · bookable for 2: early 17:30–18:15 or late from 20:15",
      slots: ["17:30", "17:45", "18:00", "18:15", "20:15", "20:30", "20:45", "21:00", "21:15", "21:30"],
    },
    menu: [
      "Melon with gochujang & pecan",
      "Green beans with nam jim",
      "Signature 'pizza bread' with achiote butter",
      "Pork chop with 'nduja béarnaise",
      "Rotating seasonal shared plates",
      "Natural & low-intervention wines",
    ],
    website: "https://restaurantcleo.dk/",
    bookUrl: "https://book.easytablebooking.com/book/?id=9833d&lang=en",
    menuUrl: "https://restaurantcleo.dk/madogdrikke/aften",
    maps: "https://maps.app.goo.gl/mmaaYzFVxMPor2y96",
    phone: "+45 38 42 42 49",
  },
];
